ramips: staging/mt7621-dma: fix build conflict
Module name conflict is a fatal error in 5.10:
  error: the following would cause module name conflict:
    drivers/dma/mediatek/mtk-hsdma.ko
    drivers/staging/mt7621-dma/mtk-hsdma.ko

This change has already been accepted upstream:
https://lore.kernel.org/driverdev-devel/20210130034507.2115280-1-ilya.lipnitskiy@gmail.com/

However, since quilt doesn't handle renames too well, instead of
backporting the patch, simply adjust the Kconfig to avoid the file
rename.

Signed-off-by: Ilya Lipnitskiy <ilya.lipnitskiy@gmail.com>